### PR TITLE
Update image-size package version

### PR DESCRIPTION
**Pull request by ryanscottaudio**
This allows certain issues w/ large JPGs to be resolved.

### CODE REVIEW

**Comment by FdezRomero** [comment]
Thanks @ryanscottaudio! I saw that the latest `image-size` version is 0.5.1, not 0.5.2.

If you make the change I will get this merged.

**Comment by ryanscottaudio** [comment]
@FdezRomero hahaha wow, sorry about that. one sec

**Comment by ryanscottaudio** [comment]
@FdezRomero should be good now!

**Comment by FdezRomero** [comment]
Great! I will fix #3 and publish a new version to NPM.

Thanks for contributing! 👍

**Pull request merged**
